// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD8siyDwiOvmUsw62DkYyMQ-2nrQKhpQk',
    appId: '1:586438514435:web:a7f7f95c6eb105eea13b36',
    messagingSenderId: '586438514435',
    projectId: 'phatchat-8ea33',
    authDomain: 'phatchat-8ea33.firebaseapp.com',
    storageBucket: 'phatchat-8ea33.firebasestorage.app',
    measurementId: 'G-NMJ89ERDS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJlkbQ4B7ISJnNFNktF5Q0dC8FWIpZsE',
    appId: '1:586438514435:android:d5cef5939aa6d737a13b36',
    messagingSenderId: '586438514435',
    projectId: 'phatchat-8ea33',
    storageBucket: 'phatchat-8ea33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauUeMJZQbBBQvxUGTopD8_Y5YM3McUaw',
    appId: '1:586438514435:ios:0a745b089d7e4250a13b36',
    messagingSenderId: '586438514435',
    projectId: 'phatchat-8ea33',
    storageBucket: 'phatchat-8ea33.firebasestorage.app',
    iosBundleId: 'com.example.phatchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauUeMJZQbBBQvxUGTopD8_Y5YM3McUaw',
    appId: '1:586438514435:ios:0a745b089d7e4250a13b36',
    messagingSenderId: '586438514435',
    projectId: 'phatchat-8ea33',
    storageBucket: 'phatchat-8ea33.firebasestorage.app',
    iosBundleId: 'com.example.phatchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD8siyDwiOvmUsw62DkYyMQ-2nrQKhpQk',
    appId: '1:586438514435:web:2a6281d8eb8988b1a13b36',
    messagingSenderId: '586438514435',
    projectId: 'phatchat-8ea33',
    authDomain: 'phatchat-8ea33.firebaseapp.com',
    storageBucket: 'phatchat-8ea33.firebasestorage.app',
    measurementId: 'G-QKPP1WMFBS',
  );
}
